const d={currentAge:42,retirementAge:56,lifeExpectancy:95,salary:124000,raisePct:3,current401k:103000,contributionPct:10,matchPct:5,rothAnnual:7000,preReturnPct:7,retReturnPct:5.5,vaMonthly:4537,vaColaPct:2.5,ssMonthly:3000,ssStartAge:67,ssColaPct:2.5,pensionMonthly:0,retSpending:80000,spendInflationPct:2.5};
const labels={currentAge:"Current Age",retirementAge:"Retirement Age",lifeExpectancy:"Life Expectancy",salary:"Annual Salary",raisePct:"Annual Raise %",current401k:"Current 401(k)",contributionPct:"401(k) Contribution %",matchPct:"Employer Match %",rothAnnual:"Annual Roth IRA",preReturnPct:"Pre-Retirement Return %",retReturnPct:"Retirement Return %",vaMonthly:"Monthly VA Disability",vaColaPct:"VA COLA %",ssMonthly:"Monthly Social Security",ssStartAge:"Social Security Start Age",ssColaPct:"SS COLA %",pensionMonthly:"Monthly Pension",retSpending:"Annual Retirement Spending",spendInflationPct:"Spending Inflation %"};
let s=JSON.parse(localStorage.getItem("vrp")||"null")||structuredClone(d),promptEvent=null;
const m=n=>(n||0).toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:0}),p=n=>n/100;
function save(){localStorage.setItem("vrp",JSON.stringify(s))}
function buildInputs(){inputs.innerHTML="";Object.keys(d).forEach(k=>{let div=document.createElement("div");div.className="inputGroup";div.innerHTML=`<label>${labels[k]}</label><input type="number" step="0.1" value="${s[k]}">`;inputs.appendChild(div);div.querySelector("input").oninput=e=>{s[k]=Number(e.target.value);save();render()}})}
function project(o={}){let x={...s,...o},rows=[],portfolio=x.current401k,salary=x.salary,va=x.vaMonthly*12,ss=x.ssMonthly*12,spend=x.retSpending;for(let age=x.currentAge;age<=x.lifeExpectancy;age++){let retired=age>=x.retirementAge,sal=retired?0:salary,contrib=retired?0:salary*(p(x.contributionPct)+p(x.matchPct))+x.rothAnnual,ssInc=age>=x.ssStartAge?ss:0,pension=retired?x.pensionMonthly*12:0,spending=retired?spend:0,withdraw=retired?Math.max(0,spending-(va+ssInc+pension)):0,rate=retired?p(x.retReturnPct):p(x.preReturnPct);portfolio=Math.max(0,(portfolio+contrib-withdraw)*(1+rate));rows.push({age,sal,contrib,va,ssInc,pension,spending,withdraw,portfolio});if(!retired)salary*=1+p(x.raisePct);va*=1+p(x.vaColaPct);if(age>=x.ssStartAge)ss*=1+p(x.ssColaPct);if(retired)spend*=1+p(x.spendInflationPct)}return rows}
function score(rows){let final=rows.at(-1).portfolio,ret=rows.find(r=>r.age===s.retirementAge)?.portfolio||1;if(final<=0)return 45;return Math.max(60,Math.min(99,Math.round(70+(final/ret)*18)))}
function render(){let rows=project(),ret=rows.find(r=>r.age===s.retirementAge)||rows[0],final=rows.at(-1),sc=score(rows);titleAge.textContent=s.retirementAge;retirePortfolio.textContent=m(ret.portfolio);finalPortfolio.textContent=m(final.portfolio);vaRetire.textContent=m(ret.va);gap.textContent=m(ret.withdraw);document.getElementById("score").textContent=sc;status.textContent=final.portfolio>0?"On Track":"Needs Attention";status.style.color=final.portfolio>0?"var(--good)":"var(--bad)";statusDetail.textContent=final.portfolio>0?`Portfolio lasts through age ${s.lifeExpectancy} under these assumptions.`:"Projection runs out before life expectancy.";rowsEl(rows);scenarioRender();draw(rows)}
function rowsEl(rows){document.getElementById("rows").innerHTML=rows.map(r=>`<tr><td>${r.age}</td><td>${m(r.sal)}</td><td>${m(r.contrib)}</td><td>${m(r.va)}</td><td>${m(r.ssInc)}</td><td>${m(r.spending)}</td><td>${m(r.withdraw)}</td><td>${m(r.portfolio)}</td></tr>`).join("")}
function scenarioRender(){let list=[["Baseline",{}],["Save 15%",{contributionPct:15}],["Retire 55",{retirementAge:55,contributionPct:15}],["Retire 60",{retirementAge:60}],["Conservative",{preReturnPct:6,retReturnPct:4.5}],["Higher Inflation",{spendInflationPct:4}]];scenarioCards.innerHTML=list.map(([name,o])=>{let rows=project(o),x={...s,...o},ret=rows.find(r=>r.age===x.retirementAge),final=rows.at(-1);return `<div class="card scenario"><h3>${name}</h3><p>Retire age: <strong>${x.retirementAge}</strong></p><p>At retirement: <strong>${m(ret?.portfolio)}</strong></p><p>At age ${x.lifeExpectancy}: <strong>${m(final.portfolio)}</strong></p></div>`}).join("")}
function draw(rows){let c=chart,ctx=c.getContext("2d"),pad=46,max=Math.max(...rows.map(r=>r.portfolio),1),minA=rows[0].age,maxA=rows.at(-1).age;ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle="#d8e0ea";for(let i=0;i<=5;i++){let y=pad+(c.height-pad*2)*i/5;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(c.width-pad,y);ctx.stroke()}ctx.strokeStyle="#2563eb";ctx.lineWidth=4;ctx.beginPath();rows.forEach((r,i)=>{let x=pad+(r.age-minA)/(maxA-minA)*(c.width-pad*2),y=c.height-pad-(r.portfolio/max)*(c.height-pad*2);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();let rx=pad+(s.retirementAge-minA)/(maxA-minA)*(c.width-pad*2);ctx.strokeStyle="#b45309";ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(rx,pad);ctx.lineTo(rx,c.height-pad);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle="#64748b";ctx.font="14px sans-serif";ctx.fillText(m(max),pad,24);ctx.fillText("Retirement",rx+6,pad+18)}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active");render()});
resetBtn.onclick=()=>{s=structuredClone(d);save();buildInputs();render()};
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();promptEvent=e;installBtn.hidden=false});
installBtn.onclick=async()=>{if(promptEvent){promptEvent.prompt();promptEvent=null;installBtn.hidden=true}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
buildInputs();render();